/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityType = { 'CaseStudy' : null } |
  { 'Assessment' : null } |
  { 'Quiz' : null } |
  { 'Unit' : null } |
  { 'VirtualLab' : null } |
  { 'Experiment' : null } |
  { 'FieldTrip' : null } |
  { 'Simulation' : null } |
  { 'Project' : null } |
  { 'Lesson' : null };
export interface EnvironmentalLaw {
  'id' : string,
  'impactScore' : bigint,
  'name' : string,
  'description' : string,
  'yearEnacted' : bigint,
  'globeImpact' : Array<GlobeImpact>,
}
export interface EnvironmentalLawProposal {
  'id' : string,
  'votingPrincipals' : Array<Principal>,
  'status' : LawProposalStatus,
  'title' : string,
  'implementationPlan' : string,
  'votesAgainst' : bigint,
  'votesFor' : bigint,
  'expectedEnvironmentalImpact' : bigint,
  'supportingArguments' : Array<string>,
  'votingDeadline' : bigint,
  'description' : string,
  'submissionDate' : bigint,
  'purpose' : string,
  'proposedBy' : Principal,
}
export interface EnvironmentalTreaty {
  'id' : string,
  'globalImpactScore' : bigint,
  'yearSigned' : bigint,
  'name' : string,
  'description' : string,
  'comparisonData' : TreatyComparisonData,
  'participatingCountries' : Array<string>,
}
export interface GlobeImpact {
  'region' : string,
  'climateChangeScore' : bigint,
  'biodiversityScore' : bigint,
  'airQualityScore' : bigint,
}
export interface InteractiveActivity {
  'id' : string,
  'title' : string,
  'activityType' : ActivityType,
  'participationData' : Array<string>,
  'completionScore' : bigint,
}
export interface InteractiveTimeline {
  'id' : string,
  'title' : string,
  'timelineEvents' : Array<TimelineEvent>,
  'globalImpactData' : Array<GlobeImpact>,
  'description' : string,
  'treatyComparison' : TreatyComparisonData,
  'interactiveActivities' : Array<InteractiveActivity>,
  'engagementScore' : bigint,
}
export type LawProposalStatus = { 'UnderReview' : null } |
  { 'VotingInProgress' : null } |
  { 'Enacted' : null } |
  { 'PendingReview' : null } |
  { 'Rejected' : null };
export type LawTimelineEventType = { 'Enacted' : null } |
  { 'Renewed' : null } |
  { 'Updated' : null } |
  { 'Implemented' : null } |
  { 'Amended' : null } |
  { 'Reviewed' : null } |
  { 'Challenged' : null } |
  { 'Expired' : null };
export interface TimelineEvent {
  'id' : string,
  'region' : string,
  'publicAwarenessData' : Array<string>,
  'timestamp' : bigint,
  'environmentalChangeScore' : bigint,
  'eventType' : LawTimelineEventType,
}
export interface TreatyComparison {
  'speciesProtectionDifference' : bigint,
  'treaty1Id' : string,
  'treaty2Id' : string,
  'complianceScoreDifference' : bigint,
  'emissionReductionDifference' : bigint,
}
export interface TreatyComparisonData {
  'reducedEmissions' : bigint,
  'protectedSpecies' : bigint,
}
export interface UserProfile {
  'quizScores' : Array<[string, bigint]>,
  'name' : string,
  'badges' : Array<string>,
  'role' : string,
  'careerReflections' : Array<string>,
  'email' : string,
  'completedUnits' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / ---------------------------------
   * / Admin Functions for Content Management
   * / ---------------------------------
   */
  'addEnvironmentalLaw' : ActorMethod<[EnvironmentalLaw], undefined>,
  'addEnvironmentalTreaty' : ActorMethod<[EnvironmentalTreaty], undefined>,
  'addInteractiveActivity' : ActorMethod<[InteractiveActivity], undefined>,
  'addInteractiveTimeline' : ActorMethod<[InteractiveTimeline], undefined>,
  'addTimelineEvent' : ActorMethod<[TimelineEvent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / ---------------------------------
   * / Teacher Dashboard Functions
   * / ---------------------------------
   */
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  /**
   * / ---------------------------------
   * / User Profile Functions
   * / ---------------------------------
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEnvironmentalLawProposal' : ActorMethod<
    [string],
    [] | [EnvironmentalLawProposal]
  >,
  'getEnvironmentalLawProposals' : ActorMethod<
    [],
    Array<EnvironmentalLawProposal>
  >,
  /**
   * / ---------------------------------
   * / Public Query Functions (Read-Only)
   * / ---------------------------------
   */
  'getEnvironmentalLaws' : ActorMethod<[], Array<EnvironmentalLaw>>,
  'getEnvironmentalTreaties' : ActorMethod<[], Array<EnvironmentalTreaty>>,
  'getInteractiveActivities' : ActorMethod<[], Array<InteractiveActivity>>,
  'getInteractiveTimelines' : ActorMethod<[], Array<InteractiveTimeline>>,
  'getStudentProgress' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getTimelineEventsByDecade' : ActorMethod<
    [bigint, bigint],
    Array<TimelineEvent>
  >,
  'getTimelineEventsByEventType' : ActorMethod<
    [LawTimelineEventType],
    Array<TimelineEvent>
  >,
  'getTimelineEventsByRegion' : ActorMethod<[string], Array<TimelineEvent>>,
  'getTreatyComparisons' : ActorMethod<[], Array<TreatyComparison>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / ---------------------------------
   * / User Profile Types and Storage
   * / ---------------------------------
   */
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / ---------------------------------
   * / Environmental Law Functions
   * / ---------------------------------
   */
  'submitEnvironmentalLawProposal' : ActorMethod<
    [EnvironmentalLawProposal],
    undefined
  >,
  'updateLawProposalStatus' : ActorMethod<
    [string, LawProposalStatus],
    undefined
  >,
  'voteForLawProposal' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];