/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GlobeImpact = IDL.Record({
  'region' : IDL.Text,
  'climateChangeScore' : IDL.Nat,
  'biodiversityScore' : IDL.Nat,
  'airQualityScore' : IDL.Nat,
});
export const EnvironmentalLaw = IDL.Record({
  'id' : IDL.Text,
  'impactScore' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'yearEnacted' : IDL.Nat,
  'globeImpact' : IDL.Vec(GlobeImpact),
});
export const TreatyComparisonData = IDL.Record({
  'reducedEmissions' : IDL.Nat,
  'protectedSpecies' : IDL.Nat,
});
export const EnvironmentalTreaty = IDL.Record({
  'id' : IDL.Text,
  'globalImpactScore' : IDL.Nat,
  'yearSigned' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'comparisonData' : TreatyComparisonData,
  'participatingCountries' : IDL.Vec(IDL.Text),
});
export const ActivityType = IDL.Variant({
  'CaseStudy' : IDL.Null,
  'Assessment' : IDL.Null,
  'Quiz' : IDL.Null,
  'Unit' : IDL.Null,
  'VirtualLab' : IDL.Null,
  'Experiment' : IDL.Null,
  'FieldTrip' : IDL.Null,
  'Simulation' : IDL.Null,
  'Project' : IDL.Null,
  'Lesson' : IDL.Null,
});
export const InteractiveActivity = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'activityType' : ActivityType,
  'participationData' : IDL.Vec(IDL.Text),
  'completionScore' : IDL.Nat,
});
export const LawTimelineEventType = IDL.Variant({
  'Enacted' : IDL.Null,
  'Renewed' : IDL.Null,
  'Updated' : IDL.Null,
  'Implemented' : IDL.Null,
  'Amended' : IDL.Null,
  'Reviewed' : IDL.Null,
  'Challenged' : IDL.Null,
  'Expired' : IDL.Null,
});
export const TimelineEvent = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'publicAwarenessData' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
  'environmentalChangeScore' : IDL.Nat,
  'eventType' : LawTimelineEventType,
});
export const InteractiveTimeline = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'timelineEvents' : IDL.Vec(TimelineEvent),
  'globalImpactData' : IDL.Vec(GlobeImpact),
  'description' : IDL.Text,
  'treatyComparison' : TreatyComparisonData,
  'interactiveActivities' : IDL.Vec(InteractiveActivity),
  'engagementScore' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'role' : IDL.Text,
  'careerReflections' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'completedUnits' : IDL.Vec(IDL.Nat),
});
export const LawProposalStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'VotingInProgress' : IDL.Null,
  'Enacted' : IDL.Null,
  'PendingReview' : IDL.Null,
  'Rejected' : IDL.Null,
});
export const EnvironmentalLawProposal = IDL.Record({
  'id' : IDL.Text,
  'votingPrincipals' : IDL.Vec(IDL.Principal),
  'status' : LawProposalStatus,
  'title' : IDL.Text,
  'implementationPlan' : IDL.Text,
  'votesAgainst' : IDL.Nat,
  'votesFor' : IDL.Nat,
  'expectedEnvironmentalImpact' : IDL.Nat,
  'supportingArguments' : IDL.Vec(IDL.Text),
  'votingDeadline' : IDL.Int,
  'description' : IDL.Text,
  'submissionDate' : IDL.Int,
  'purpose' : IDL.Text,
  'proposedBy' : IDL.Principal,
});
export const TreatyComparison = IDL.Record({
  'speciesProtectionDifference' : IDL.Int,
  'treaty1Id' : IDL.Text,
  'treaty2Id' : IDL.Text,
  'complianceScoreDifference' : IDL.Int,
  'emissionReductionDifference' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEnvironmentalLaw' : IDL.Func([EnvironmentalLaw], [], []),
  'addEnvironmentalTreaty' : IDL.Func([EnvironmentalTreaty], [], []),
  'addInteractiveActivity' : IDL.Func([InteractiveActivity], [], []),
  'addInteractiveTimeline' : IDL.Func([InteractiveTimeline], [], []),
  'addTimelineEvent' : IDL.Func([TimelineEvent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEnvironmentalLawProposal' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EnvironmentalLawProposal)],
      ['query'],
    ),
  'getEnvironmentalLawProposals' : IDL.Func(
      [],
      [IDL.Vec(EnvironmentalLawProposal)],
      ['query'],
    ),
  'getEnvironmentalLaws' : IDL.Func([], [IDL.Vec(EnvironmentalLaw)], ['query']),
  'getEnvironmentalTreaties' : IDL.Func(
      [],
      [IDL.Vec(EnvironmentalTreaty)],
      ['query'],
    ),
  'getInteractiveActivities' : IDL.Func(
      [],
      [IDL.Vec(InteractiveActivity)],
      ['query'],
    ),
  'getInteractiveTimelines' : IDL.Func(
      [],
      [IDL.Vec(InteractiveTimeline)],
      ['query'],
    ),
  'getStudentProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getTimelineEventsByDecade' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(TimelineEvent)],
      ['query'],
    ),
  'getTimelineEventsByEventType' : IDL.Func(
      [LawTimelineEventType],
      [IDL.Vec(TimelineEvent)],
      ['query'],
    ),
  'getTimelineEventsByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimelineEvent)],
      ['query'],
    ),
  'getTreatyComparisons' : IDL.Func([], [IDL.Vec(TreatyComparison)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEnvironmentalLawProposal' : IDL.Func(
      [EnvironmentalLawProposal],
      [],
      [],
    ),
  'updateLawProposalStatus' : IDL.Func([IDL.Text, LawProposalStatus], [], []),
  'voteForLawProposal' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GlobeImpact = IDL.Record({
    'region' : IDL.Text,
    'climateChangeScore' : IDL.Nat,
    'biodiversityScore' : IDL.Nat,
    'airQualityScore' : IDL.Nat,
  });
  const EnvironmentalLaw = IDL.Record({
    'id' : IDL.Text,
    'impactScore' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'yearEnacted' : IDL.Nat,
    'globeImpact' : IDL.Vec(GlobeImpact),
  });
  const TreatyComparisonData = IDL.Record({
    'reducedEmissions' : IDL.Nat,
    'protectedSpecies' : IDL.Nat,
  });
  const EnvironmentalTreaty = IDL.Record({
    'id' : IDL.Text,
    'globalImpactScore' : IDL.Nat,
    'yearSigned' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'comparisonData' : TreatyComparisonData,
    'participatingCountries' : IDL.Vec(IDL.Text),
  });
  const ActivityType = IDL.Variant({
    'CaseStudy' : IDL.Null,
    'Assessment' : IDL.Null,
    'Quiz' : IDL.Null,
    'Unit' : IDL.Null,
    'VirtualLab' : IDL.Null,
    'Experiment' : IDL.Null,
    'FieldTrip' : IDL.Null,
    'Simulation' : IDL.Null,
    'Project' : IDL.Null,
    'Lesson' : IDL.Null,
  });
  const InteractiveActivity = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'activityType' : ActivityType,
    'participationData' : IDL.Vec(IDL.Text),
    'completionScore' : IDL.Nat,
  });
  const LawTimelineEventType = IDL.Variant({
    'Enacted' : IDL.Null,
    'Renewed' : IDL.Null,
    'Updated' : IDL.Null,
    'Implemented' : IDL.Null,
    'Amended' : IDL.Null,
    'Reviewed' : IDL.Null,
    'Challenged' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const TimelineEvent = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'publicAwarenessData' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
    'environmentalChangeScore' : IDL.Nat,
    'eventType' : LawTimelineEventType,
  });
  const InteractiveTimeline = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'timelineEvents' : IDL.Vec(TimelineEvent),
    'globalImpactData' : IDL.Vec(GlobeImpact),
    'description' : IDL.Text,
    'treatyComparison' : TreatyComparisonData,
    'interactiveActivities' : IDL.Vec(InteractiveActivity),
    'engagementScore' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'role' : IDL.Text,
    'careerReflections' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'completedUnits' : IDL.Vec(IDL.Nat),
  });
  const LawProposalStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'VotingInProgress' : IDL.Null,
    'Enacted' : IDL.Null,
    'PendingReview' : IDL.Null,
    'Rejected' : IDL.Null,
  });
  const EnvironmentalLawProposal = IDL.Record({
    'id' : IDL.Text,
    'votingPrincipals' : IDL.Vec(IDL.Principal),
    'status' : LawProposalStatus,
    'title' : IDL.Text,
    'implementationPlan' : IDL.Text,
    'votesAgainst' : IDL.Nat,
    'votesFor' : IDL.Nat,
    'expectedEnvironmentalImpact' : IDL.Nat,
    'supportingArguments' : IDL.Vec(IDL.Text),
    'votingDeadline' : IDL.Int,
    'description' : IDL.Text,
    'submissionDate' : IDL.Int,
    'purpose' : IDL.Text,
    'proposedBy' : IDL.Principal,
  });
  const TreatyComparison = IDL.Record({
    'speciesProtectionDifference' : IDL.Int,
    'treaty1Id' : IDL.Text,
    'treaty2Id' : IDL.Text,
    'complianceScoreDifference' : IDL.Int,
    'emissionReductionDifference' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEnvironmentalLaw' : IDL.Func([EnvironmentalLaw], [], []),
    'addEnvironmentalTreaty' : IDL.Func([EnvironmentalTreaty], [], []),
    'addInteractiveActivity' : IDL.Func([InteractiveActivity], [], []),
    'addInteractiveTimeline' : IDL.Func([InteractiveTimeline], [], []),
    'addTimelineEvent' : IDL.Func([TimelineEvent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEnvironmentalLawProposal' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EnvironmentalLawProposal)],
        ['query'],
      ),
    'getEnvironmentalLawProposals' : IDL.Func(
        [],
        [IDL.Vec(EnvironmentalLawProposal)],
        ['query'],
      ),
    'getEnvironmentalLaws' : IDL.Func(
        [],
        [IDL.Vec(EnvironmentalLaw)],
        ['query'],
      ),
    'getEnvironmentalTreaties' : IDL.Func(
        [],
        [IDL.Vec(EnvironmentalTreaty)],
        ['query'],
      ),
    'getInteractiveActivities' : IDL.Func(
        [],
        [IDL.Vec(InteractiveActivity)],
        ['query'],
      ),
    'getInteractiveTimelines' : IDL.Func(
        [],
        [IDL.Vec(InteractiveTimeline)],
        ['query'],
      ),
    'getStudentProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getTimelineEventsByDecade' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'getTimelineEventsByEventType' : IDL.Func(
        [LawTimelineEventType],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'getTimelineEventsByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'getTreatyComparisons' : IDL.Func(
        [],
        [IDL.Vec(TreatyComparison)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEnvironmentalLawProposal' : IDL.Func(
        [EnvironmentalLawProposal],
        [],
        [],
      ),
    'updateLawProposalStatus' : IDL.Func([IDL.Text, LawProposalStatus], [], []),
    'voteForLawProposal' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };