/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface EnvironmentalLaw {
    id: string;
    impactScore: bigint;
    name: string;
    description: string;
    yearEnacted: bigint;
    globeImpact: Array<GlobeImpact>;
}
export interface TreatyComparison {
    speciesProtectionDifference: bigint;
    treaty1Id: string;
    treaty2Id: string;
    complianceScoreDifference: bigint;
    emissionReductionDifference: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface EnvironmentalTreaty {
    id: string;
    globalImpactScore: bigint;
    yearSigned: bigint;
    name: string;
    description: string;
    comparisonData: TreatyComparisonData;
    participatingCountries: Array<string>;
}
export interface InteractiveTimeline {
    id: string;
    title: string;
    timelineEvents: Array<TimelineEvent>;
    globalImpactData: Array<GlobeImpact>;
    description: string;
    treatyComparison: TreatyComparisonData;
    interactiveActivities: Array<InteractiveActivity>;
    engagementScore: bigint;
}
export interface EnvironmentalLawProposal {
    id: string;
    votingPrincipals: Array<Principal>;
    status: LawProposalStatus;
    title: string;
    implementationPlan: string;
    votesAgainst: bigint;
    votesFor: bigint;
    expectedEnvironmentalImpact: bigint;
    supportingArguments: Array<string>;
    votingDeadline: bigint;
    description: string;
    submissionDate: bigint;
    purpose: string;
    proposedBy: Principal;
}
export interface TreatyComparisonData {
    reducedEmissions: bigint;
    protectedSpecies: bigint;
}
export interface TimelineEvent {
    id: string;
    region: string;
    publicAwarenessData: Array<string>;
    timestamp: bigint;
    environmentalChangeScore: bigint;
    eventType: LawTimelineEventType;
}
export interface GlobeImpact {
    region: string;
    climateChangeScore: bigint;
    biodiversityScore: bigint;
    airQualityScore: bigint;
}
export interface InteractiveActivity {
    id: string;
    title: string;
    activityType: ActivityType;
    participationData: Array<string>;
    completionScore: bigint;
}
export interface UserProfile {
    quizScores: Array<[string, bigint]>;
    name: string;
    badges: Array<string>;
    role: string;
    careerReflections: Array<string>;
    email: string;
    completedUnits: Array<bigint>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ActivityType {
    CaseStudy = "CaseStudy",
    Assessment = "Assessment",
    Quiz = "Quiz",
    Unit = "Unit",
    VirtualLab = "VirtualLab",
    Experiment = "Experiment",
    FieldTrip = "FieldTrip",
    Simulation = "Simulation",
    Project = "Project",
    Lesson = "Lesson"
}
export enum LawProposalStatus {
    UnderReview = "UnderReview",
    VotingInProgress = "VotingInProgress",
    Enacted = "Enacted",
    PendingReview = "PendingReview",
    Rejected = "Rejected"
}
export enum LawTimelineEventType {
    Enacted = "Enacted",
    Renewed = "Renewed",
    Updated = "Updated",
    Implemented = "Implemented",
    Amended = "Amended",
    Reviewed = "Reviewed",
    Challenged = "Challenged",
    Expired = "Expired"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / ---------------------------------
     * / Admin Functions for Content Management
     * / ---------------------------------
     */
    addEnvironmentalLaw(law: EnvironmentalLaw): Promise<void>;
    addEnvironmentalTreaty(treaty: EnvironmentalTreaty): Promise<void>;
    addInteractiveActivity(activity: InteractiveActivity): Promise<void>;
    addInteractiveTimeline(timeline: InteractiveTimeline): Promise<void>;
    addTimelineEvent(event: TimelineEvent): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / ---------------------------------
     * / Teacher Dashboard Functions
     * / ---------------------------------
     */
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    /**
     * / ---------------------------------
     * / User Profile Functions
     * / ---------------------------------
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEnvironmentalLawProposal(proposalId: string): Promise<EnvironmentalLawProposal | null>;
    getEnvironmentalLawProposals(): Promise<Array<EnvironmentalLawProposal>>;
    /**
     * / ---------------------------------
     * / Public Query Functions (Read-Only)
     * / ---------------------------------
     */
    getEnvironmentalLaws(): Promise<Array<EnvironmentalLaw>>;
    getEnvironmentalTreaties(): Promise<Array<EnvironmentalTreaty>>;
    getInteractiveActivities(): Promise<Array<InteractiveActivity>>;
    getInteractiveTimelines(): Promise<Array<InteractiveTimeline>>;
    getStudentProgress(student: Principal): Promise<UserProfile | null>;
    getTimelineEventsByDecade(decadeStartYear: bigint, decadeEndYear: bigint): Promise<Array<TimelineEvent>>;
    getTimelineEventsByEventType(eventType: LawTimelineEventType): Promise<Array<TimelineEvent>>;
    getTimelineEventsByRegion(region: string): Promise<Array<TimelineEvent>>;
    getTreatyComparisons(): Promise<Array<TreatyComparison>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / ---------------------------------
     * / User Profile Types and Storage
     * / ---------------------------------
     */
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / ---------------------------------
     * / Environmental Law Functions
     * / ---------------------------------
     */
    submitEnvironmentalLawProposal(proposal: EnvironmentalLawProposal): Promise<void>;
    updateLawProposalStatus(proposalId: string, status: LawProposalStatus): Promise<void>;
    voteForLawProposal(proposalId: string, isFor: boolean): Promise<void>;
}
import type { ActivityType as _ActivityType, EnvironmentalLawProposal as _EnvironmentalLawProposal, GlobeImpact as _GlobeImpact, InteractiveActivity as _InteractiveActivity, InteractiveTimeline as _InteractiveTimeline, LawProposalStatus as _LawProposalStatus, LawTimelineEventType as _LawTimelineEventType, TimelineEvent as _TimelineEvent, TreatyComparisonData as _TreatyComparisonData, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEnvironmentalLaw(arg0: EnvironmentalLaw): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEnvironmentalLaw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEnvironmentalLaw(arg0);
            return result;
        }
    }
    async addEnvironmentalTreaty(arg0: EnvironmentalTreaty): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEnvironmentalTreaty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEnvironmentalTreaty(arg0);
            return result;
        }
    }
    async addInteractiveActivity(arg0: InteractiveActivity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInteractiveActivity(to_candid_InteractiveActivity_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInteractiveActivity(to_candid_InteractiveActivity_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInteractiveTimeline(arg0: InteractiveTimeline): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInteractiveTimeline(to_candid_InteractiveTimeline_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInteractiveTimeline(to_candid_InteractiveTimeline_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTimelineEvent(arg0: TimelineEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimelineEvent(to_candid_TimelineEvent_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimelineEvent(to_candid_TimelineEvent_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnvironmentalLawProposal(arg0: string): Promise<EnvironmentalLawProposal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnvironmentalLawProposal(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnvironmentalLawProposal(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnvironmentalLawProposals(): Promise<Array<EnvironmentalLawProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnvironmentalLawProposals();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnvironmentalLawProposals();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnvironmentalLaws(): Promise<Array<EnvironmentalLaw>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnvironmentalLaws();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnvironmentalLaws();
            return result;
        }
    }
    async getEnvironmentalTreaties(): Promise<Array<EnvironmentalTreaty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnvironmentalTreaties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnvironmentalTreaties();
            return result;
        }
    }
    async getInteractiveActivities(): Promise<Array<InteractiveActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractiveActivities();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractiveActivities();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInteractiveTimelines(): Promise<Array<InteractiveTimeline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractiveTimelines();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractiveTimelines();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProgress(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProgress(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProgress(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimelineEventsByDecade(arg0: bigint, arg1: bigint): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimelineEventsByDecade(arg0, arg1);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimelineEventsByDecade(arg0, arg1);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimelineEventsByEventType(arg0: LawTimelineEventType): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimelineEventsByEventType(to_candid_LawTimelineEventType_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimelineEventsByEventType(to_candid_LawTimelineEventType_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimelineEventsByRegion(arg0: string): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimelineEventsByRegion(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimelineEventsByRegion(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreatyComparisons(): Promise<Array<TreatyComparison>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreatyComparisons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreatyComparisons();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitEnvironmentalLawProposal(arg0: EnvironmentalLawProposal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnvironmentalLawProposal(to_candid_EnvironmentalLawProposal_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnvironmentalLawProposal(to_candid_EnvironmentalLawProposal_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLawProposalStatus(arg0: string, arg1: LawProposalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLawProposalStatus(arg0, to_candid_LawProposalStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLawProposalStatus(arg0, to_candid_LawProposalStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async voteForLawProposal(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteForLawProposal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteForLawProposal(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ActivityType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_EnvironmentalLawProposal_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnvironmentalLawProposal): EnvironmentalLawProposal {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_InteractiveActivity_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteractiveActivity): InteractiveActivity {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_InteractiveTimeline_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteractiveTimeline): InteractiveTimeline {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_LawProposalStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LawProposalStatus): LawProposalStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_LawTimelineEventType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LawTimelineEventType): LawTimelineEventType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineEvent_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEvent): TimelineEvent {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EnvironmentalLawProposal]): EnvironmentalLawProposal | null {
    return value.length === 0 ? null : from_candid_EnvironmentalLawProposal_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    votingPrincipals: Array<Principal>;
    status: _LawProposalStatus;
    title: string;
    implementationPlan: string;
    votesAgainst: bigint;
    votesFor: bigint;
    expectedEnvironmentalImpact: bigint;
    supportingArguments: Array<string>;
    votingDeadline: bigint;
    description: string;
    submissionDate: bigint;
    purpose: string;
    proposedBy: Principal;
}): {
    id: string;
    votingPrincipals: Array<Principal>;
    status: LawProposalStatus;
    title: string;
    implementationPlan: string;
    votesAgainst: bigint;
    votesFor: bigint;
    expectedEnvironmentalImpact: bigint;
    supportingArguments: Array<string>;
    votingDeadline: bigint;
    description: string;
    submissionDate: bigint;
    purpose: string;
    proposedBy: Principal;
} {
    return {
        id: value.id,
        votingPrincipals: value.votingPrincipals,
        status: from_candid_LawProposalStatus_n28(_uploadFile, _downloadFile, value.status),
        title: value.title,
        implementationPlan: value.implementationPlan,
        votesAgainst: value.votesAgainst,
        votesFor: value.votesFor,
        expectedEnvironmentalImpact: value.expectedEnvironmentalImpact,
        supportingArguments: value.supportingArguments,
        votingDeadline: value.votingDeadline,
        description: value.description,
        submissionDate: value.submissionDate,
        purpose: value.purpose,
        proposedBy: value.proposedBy
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    activityType: _ActivityType;
    participationData: Array<string>;
    completionScore: bigint;
}): {
    id: string;
    title: string;
    activityType: ActivityType;
    participationData: Array<string>;
    completionScore: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        activityType: from_candid_ActivityType_n34(_uploadFile, _downloadFile, value.activityType),
        participationData: value.participationData,
        completionScore: value.completionScore
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    timelineEvents: Array<_TimelineEvent>;
    globalImpactData: Array<_GlobeImpact>;
    description: string;
    treatyComparison: _TreatyComparisonData;
    interactiveActivities: Array<_InteractiveActivity>;
    engagementScore: bigint;
}): {
    id: string;
    title: string;
    timelineEvents: Array<TimelineEvent>;
    globalImpactData: Array<GlobeImpact>;
    description: string;
    treatyComparison: TreatyComparisonData;
    interactiveActivities: Array<InteractiveActivity>;
    engagementScore: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        timelineEvents: from_candid_vec_n39(_uploadFile, _downloadFile, value.timelineEvents),
        globalImpactData: value.globalImpactData,
        description: value.description,
        treatyComparison: value.treatyComparison,
        interactiveActivities: from_candid_vec_n31(_uploadFile, _downloadFile, value.interactiveActivities),
        engagementScore: value.engagementScore
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    publicAwarenessData: Array<string>;
    timestamp: bigint;
    environmentalChangeScore: bigint;
    eventType: _LawTimelineEventType;
}): {
    id: string;
    region: string;
    publicAwarenessData: Array<string>;
    timestamp: bigint;
    environmentalChangeScore: bigint;
    eventType: LawTimelineEventType;
} {
    return {
        id: value.id,
        region: value.region,
        publicAwarenessData: value.publicAwarenessData,
        timestamp: value.timestamp,
        environmentalChangeScore: value.environmentalChangeScore,
        eventType: from_candid_LawTimelineEventType_n42(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UnderReview: null;
} | {
    VotingInProgress: null;
} | {
    Enacted: null;
} | {
    PendingReview: null;
} | {
    Rejected: null;
}): LawProposalStatus {
    return "UnderReview" in value ? LawProposalStatus.UnderReview : "VotingInProgress" in value ? LawProposalStatus.VotingInProgress : "Enacted" in value ? LawProposalStatus.Enacted : "PendingReview" in value ? LawProposalStatus.PendingReview : "Rejected" in value ? LawProposalStatus.Rejected : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CaseStudy: null;
} | {
    Assessment: null;
} | {
    Quiz: null;
} | {
    Unit: null;
} | {
    VirtualLab: null;
} | {
    Experiment: null;
} | {
    FieldTrip: null;
} | {
    Simulation: null;
} | {
    Project: null;
} | {
    Lesson: null;
}): ActivityType {
    return "CaseStudy" in value ? ActivityType.CaseStudy : "Assessment" in value ? ActivityType.Assessment : "Quiz" in value ? ActivityType.Quiz : "Unit" in value ? ActivityType.Unit : "VirtualLab" in value ? ActivityType.VirtualLab : "Experiment" in value ? ActivityType.Experiment : "FieldTrip" in value ? ActivityType.FieldTrip : "Simulation" in value ? ActivityType.Simulation : "Project" in value ? ActivityType.Project : "Lesson" in value ? ActivityType.Lesson : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Enacted: null;
} | {
    Renewed: null;
} | {
    Updated: null;
} | {
    Implemented: null;
} | {
    Amended: null;
} | {
    Reviewed: null;
} | {
    Challenged: null;
} | {
    Expired: null;
}): LawTimelineEventType {
    return "Enacted" in value ? LawTimelineEventType.Enacted : "Renewed" in value ? LawTimelineEventType.Renewed : "Updated" in value ? LawTimelineEventType.Updated : "Implemented" in value ? LawTimelineEventType.Implemented : "Amended" in value ? LawTimelineEventType.Amended : "Reviewed" in value ? LawTimelineEventType.Reviewed : "Challenged" in value ? LawTimelineEventType.Challenged : "Expired" in value ? LawTimelineEventType.Expired : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EnvironmentalLawProposal>): Array<EnvironmentalLawProposal> {
    return value.map((x)=>from_candid_EnvironmentalLawProposal_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InteractiveActivity>): Array<InteractiveActivity> {
    return value.map((x)=>from_candid_InteractiveActivity_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InteractiveTimeline>): Array<InteractiveTimeline> {
    return value.map((x)=>from_candid_InteractiveTimeline_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimelineEvent>): Array<TimelineEvent> {
    return value.map((x)=>from_candid_TimelineEvent_n40(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_EnvironmentalLawProposal_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnvironmentalLawProposal): _EnvironmentalLawProposal {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_InteractiveActivity_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractiveActivity): _InteractiveActivity {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_InteractiveTimeline_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractiveTimeline): _InteractiveTimeline {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_LawProposalStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LawProposalStatus): _LawProposalStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_LawTimelineEventType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LawTimelineEventType): _LawTimelineEventType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TimelineEvent_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineEvent): _TimelineEvent {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    timelineEvents: Array<TimelineEvent>;
    globalImpactData: Array<GlobeImpact>;
    description: string;
    treatyComparison: TreatyComparisonData;
    interactiveActivities: Array<InteractiveActivity>;
    engagementScore: bigint;
}): {
    id: string;
    title: string;
    timelineEvents: Array<_TimelineEvent>;
    globalImpactData: Array<_GlobeImpact>;
    description: string;
    treatyComparison: _TreatyComparisonData;
    interactiveActivities: Array<_InteractiveActivity>;
    engagementScore: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        timelineEvents: to_candid_vec_n14(_uploadFile, _downloadFile, value.timelineEvents),
        globalImpactData: value.globalImpactData,
        description: value.description,
        treatyComparison: value.treatyComparison,
        interactiveActivities: to_candid_vec_n19(_uploadFile, _downloadFile, value.interactiveActivities),
        engagementScore: value.engagementScore
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    publicAwarenessData: Array<string>;
    timestamp: bigint;
    environmentalChangeScore: bigint;
    eventType: LawTimelineEventType;
}): {
    id: string;
    region: string;
    publicAwarenessData: Array<string>;
    timestamp: bigint;
    environmentalChangeScore: bigint;
    eventType: _LawTimelineEventType;
} {
    return {
        id: value.id,
        region: value.region,
        publicAwarenessData: value.publicAwarenessData,
        timestamp: value.timestamp,
        environmentalChangeScore: value.environmentalChangeScore,
        eventType: to_candid_LawTimelineEventType_n17(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    votingPrincipals: Array<Principal>;
    status: LawProposalStatus;
    title: string;
    implementationPlan: string;
    votesAgainst: bigint;
    votesFor: bigint;
    expectedEnvironmentalImpact: bigint;
    supportingArguments: Array<string>;
    votingDeadline: bigint;
    description: string;
    submissionDate: bigint;
    purpose: string;
    proposedBy: Principal;
}): {
    id: string;
    votingPrincipals: Array<Principal>;
    status: _LawProposalStatus;
    title: string;
    implementationPlan: string;
    votesAgainst: bigint;
    votesFor: bigint;
    expectedEnvironmentalImpact: bigint;
    supportingArguments: Array<string>;
    votingDeadline: bigint;
    description: string;
    submissionDate: bigint;
    purpose: string;
    proposedBy: Principal;
} {
    return {
        id: value.id,
        votingPrincipals: value.votingPrincipals,
        status: to_candid_LawProposalStatus_n46(_uploadFile, _downloadFile, value.status),
        title: value.title,
        implementationPlan: value.implementationPlan,
        votesAgainst: value.votesAgainst,
        votesFor: value.votesFor,
        expectedEnvironmentalImpact: value.expectedEnvironmentalImpact,
        supportingArguments: value.supportingArguments,
        votingDeadline: value.votingDeadline,
        description: value.description,
        submissionDate: value.submissionDate,
        purpose: value.purpose,
        proposedBy: value.proposedBy
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    activityType: ActivityType;
    participationData: Array<string>;
    completionScore: bigint;
}): {
    id: string;
    title: string;
    activityType: _ActivityType;
    participationData: Array<string>;
    completionScore: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        activityType: to_candid_ActivityType_n10(_uploadFile, _downloadFile, value.activityType),
        participationData: value.participationData,
        completionScore: value.completionScore
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    CaseStudy: null;
} | {
    Assessment: null;
} | {
    Quiz: null;
} | {
    Unit: null;
} | {
    VirtualLab: null;
} | {
    Experiment: null;
} | {
    FieldTrip: null;
} | {
    Simulation: null;
} | {
    Project: null;
} | {
    Lesson: null;
} {
    return value == ActivityType.CaseStudy ? {
        CaseStudy: null
    } : value == ActivityType.Assessment ? {
        Assessment: null
    } : value == ActivityType.Quiz ? {
        Quiz: null
    } : value == ActivityType.Unit ? {
        Unit: null
    } : value == ActivityType.VirtualLab ? {
        VirtualLab: null
    } : value == ActivityType.Experiment ? {
        Experiment: null
    } : value == ActivityType.FieldTrip ? {
        FieldTrip: null
    } : value == ActivityType.Simulation ? {
        Simulation: null
    } : value == ActivityType.Project ? {
        Project: null
    } : value == ActivityType.Lesson ? {
        Lesson: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LawTimelineEventType): {
    Enacted: null;
} | {
    Renewed: null;
} | {
    Updated: null;
} | {
    Implemented: null;
} | {
    Amended: null;
} | {
    Reviewed: null;
} | {
    Challenged: null;
} | {
    Expired: null;
} {
    return value == LawTimelineEventType.Enacted ? {
        Enacted: null
    } : value == LawTimelineEventType.Renewed ? {
        Renewed: null
    } : value == LawTimelineEventType.Updated ? {
        Updated: null
    } : value == LawTimelineEventType.Implemented ? {
        Implemented: null
    } : value == LawTimelineEventType.Amended ? {
        Amended: null
    } : value == LawTimelineEventType.Reviewed ? {
        Reviewed: null
    } : value == LawTimelineEventType.Challenged ? {
        Challenged: null
    } : value == LawTimelineEventType.Expired ? {
        Expired: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LawProposalStatus): {
    UnderReview: null;
} | {
    VotingInProgress: null;
} | {
    Enacted: null;
} | {
    PendingReview: null;
} | {
    Rejected: null;
} {
    return value == LawProposalStatus.UnderReview ? {
        UnderReview: null
    } : value == LawProposalStatus.VotingInProgress ? {
        VotingInProgress: null
    } : value == LawProposalStatus.Enacted ? {
        Enacted: null
    } : value == LawProposalStatus.PendingReview ? {
        PendingReview: null
    } : value == LawProposalStatus.Rejected ? {
        Rejected: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TimelineEvent>): Array<_TimelineEvent> {
    return value.map((x)=>to_candid_TimelineEvent_n15(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InteractiveActivity>): Array<_InteractiveActivity> {
    return value.map((x)=>to_candid_InteractiveActivity_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
